/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { AreaDetailsLocation } from './areaDetailsLocation';
import type { AreaDetailsOwnerId } from './areaDetailsOwnerId';
import type { AreaDetailsCreatedAt } from './areaDetailsCreatedAt';

export interface AreaDetails {
  name: string;
  location?: AreaDetailsLocation;
  owner_id?: AreaDetailsOwnerId;
  id: string;
  employee_count?: number;
  user_count?: number;
  created_at?: AreaDetailsCreatedAt;
}
