/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { AreaReadLocation } from './areaReadLocation';
import type { AreaReadOwnerId } from './areaReadOwnerId';

export interface AreaRead {
  name: string;
  location?: AreaReadLocation;
  owner_id?: AreaReadOwnerId;
  id: string;
}
