/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { AreaUpdateName } from './areaUpdateName';
import type { AreaUpdateLocation } from './areaUpdateLocation';

export interface AreaUpdate {
  name: AreaUpdateName;
  location: AreaUpdateLocation;
}
