/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { AreaCreateLocation } from './areaCreateLocation';
import type { AreaCreateOwnerId } from './areaCreateOwnerId';

export interface AreaCreate {
  name: string;
  location?: AreaCreateLocation;
  owner_id?: AreaCreateOwnerId;
}
