/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeCreateLastName } from './employeeCreateLastName';

export interface EmployeeCreate {
  first_name: string;
  last_name: EmployeeCreateLastName;
  phone: string;
  adress: string;
  area_id: string;
}
