/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeUpdateFirstName } from './employeeUpdateFirstName';
import type { EmployeeUpdateLastName } from './employeeUpdateLastName';
import type { EmployeeUpdatePhone } from './employeeUpdatePhone';
import type { EmployeeUpdateAdress } from './employeeUpdateAdress';

export interface EmployeeUpdate {
  first_name?: EmployeeUpdateFirstName;
  last_name?: EmployeeUpdateLastName;
  phone?: EmployeeUpdatePhone;
  adress?: EmployeeUpdateAdress;
}
