/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeReadLastName } from './employeeReadLastName';
import type { EmployeeReadUserId } from './employeeReadUserId';

export interface EmployeeRead {
  first_name: string;
  last_name: EmployeeReadLastName;
  phone: string;
  adress: string;
  id: string;
  area_id: string;
  user_id: EmployeeReadUserId;
}
