/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */

export type MovementProductTrackParams = {
area_id: number;
date_begin: Date;
date_end: Date;
skip?: number;
limit?: number;
};
