/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UserRead } from './userRead';

export interface OwnersRead {
  data: UserRead[];
  total: number;
  total_active: number;
  total_pos: number;
}
