/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { PriceType } from './priceType';

export interface PriceHistoryRead {
  product_id: number;
  type: PriceType;
  value: number;
  id: number;
  date: Date;
}
