/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */

export type PriceType = typeof PriceType[keyof typeof PriceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PriceType = {
  sale: 'sale',
  purchase: 'purchase',
} as const;
