/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */

export interface PrivateUserCreate {
  email: string;
  password: string;
  full_name: string;
  is_verified?: boolean;
}
