/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { ProductCreateDescription } from './productCreateDescription';
import type { ProductCreateCategoryName } from './productCreateCategoryName';
import type { ProductCreatePurchasePrice } from './productCreatePurchasePrice';
import type { ProductCreateInitStock } from './productCreateInitStock';
import type { ProductCreateActualStock } from './productCreateActualStock';

export interface ProductCreate {
  reference: string;
  name: string;
  description: ProductCreateDescription;
  category_name: ProductCreateCategoryName;
  area_id: string;
  price: number;
  purchase_price: ProductCreatePurchasePrice;
  init_stock: ProductCreateInitStock;
  actual_stock: ProductCreateActualStock;
}
