/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */

export type ProductCreationState = typeof ProductCreationState[keyof typeof ProductCreationState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductCreationState = {
  pending: 'pending',
  valided: 'valided',
  rejected: 'rejected',
} as const;
