/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { ProductReadDescription } from './productReadDescription';
import type { ProductReadCategoryName } from './productReadCategoryName';
import type { ProductReadPurchasePrice } from './productReadPurchasePrice';
import type { ProductReadInitStock } from './productReadInitStock';
import type { ProductReadActualStock } from './productReadActualStock';
import type { ProductCreationState } from './productCreationState';

export interface ProductRead {
  reference: string;
  name: string;
  description: ProductReadDescription;
  category_name: ProductReadCategoryName;
  area_id: number;
  price: number;
  purchase_price: ProductReadPurchasePrice;
  init_stock: ProductReadInitStock;
  actual_stock: ProductReadActualStock;
  id: number;
  state: ProductCreationState;
}
