/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { ProductDashbordReadDescription } from './productDashbordReadDescription';
import type { ProductDashbordReadCategoryName } from './productDashbordReadCategoryName';
import type { ProductDashbordReadPurchasePrice } from './productDashbordReadPurchasePrice';
import type { ProductDashbordReadInitStock } from './productDashbordReadInitStock';
import type { ProductDashbordReadActualStock } from './productDashbordReadActualStock';
import type { ProductCreationState } from './productCreationState';
import type { ProductDashbordReadIncomingQuantity } from './productDashbordReadIncomingQuantity';
import type { ProductDashbordReadOutgoingQuantity } from './productDashbordReadOutgoingQuantity';

export interface ProductDashbordRead {
  reference: string;
  name: string;
  description: ProductDashbordReadDescription;
  category_name: ProductDashbordReadCategoryName;
  area_id: number;
  price: number;
  purchase_price: ProductDashbordReadPurchasePrice;
  init_stock: ProductDashbordReadInitStock;
  actual_stock: ProductDashbordReadActualStock;
  id: number;
  state: ProductCreationState;
  incoming_quantity?: ProductDashbordReadIncomingQuantity;
  outgoing_quantity?: ProductDashbordReadOutgoingQuantity;
}
