/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { ProductCategoryUpdateAreaId } from './productCategoryUpdateAreaId';
import type { ProductCategoryUpdateCatName } from './productCategoryUpdateCatName';

export interface ProductCategoryUpdate {
  area_id: ProductCategoryUpdateAreaId;
  cat_name: ProductCategoryUpdateCatName;
}
