/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { PriceType } from './priceType';

export type ProductPriceHistoryParams = {
area_id: string;
type: PriceType;
skip?: number;
limit?: number;
};
