/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { ProductUpdateReference } from './productUpdateReference';
import type { ProductUpdateName } from './productUpdateName';
import type { ProductUpdateDescription } from './productUpdateDescription';
import type { ProductUpdateCategoryName } from './productUpdateCategoryName';
import type { ProductUpdateAreaId } from './productUpdateAreaId';
import type { ProductUpdateState } from './productUpdateState';
import type { ProductUpdateSalePrice } from './productUpdateSalePrice';
import type { ProductUpdatePurchasePrice } from './productUpdatePurchasePrice';
import type { ProductUpdateInitStock } from './productUpdateInitStock';
import type { ProductUpdateActualStock } from './productUpdateActualStock';
import type { ProductUpdateComment } from './productUpdateComment';
import type { ProductUpdateUpdatedById } from './productUpdateUpdatedById';

export interface ProductUpdate {
  reference?: ProductUpdateReference;
  name?: ProductUpdateName;
  description?: ProductUpdateDescription;
  category_name?: ProductUpdateCategoryName;
  area_id?: ProductUpdateAreaId;
  state?: ProductUpdateState;
  sale_price?: ProductUpdateSalePrice;
  purchase_price?: ProductUpdatePurchasePrice;
  init_stock?: ProductUpdateInitStock;
  actual_stock?: ProductUpdateActualStock;
  comment?: ProductUpdateComment;
  updated_by_id?: ProductUpdateUpdatedById;
}
