/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { RoleReadDescription } from './roleReadDescription';
import type { RoleReadPermission } from './roleReadPermission';

export interface RoleRead {
  name: string;
  description: RoleReadDescription;
  permission: RoleReadPermission;
  id: string;
}
