/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementCreateDateof } from './stockMovementCreateDateof';
import type { StockMovementCreateQuantity } from './stockMovementCreateQuantity';
import type { StockMovementCreateComment } from './stockMovementCreateComment';

export interface StockMovementCreate {
  area_id: number;
  product_id: number;
  direction: string;
  operation: string;
  dateof: StockMovementCreateDateof;
  quantity?: StockMovementCreateQuantity;
  comment?: StockMovementCreateComment;
  created_by: number;
  initiated_by: number;
  operation_id: number;
}
