/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementCreateProductLotId } from './stockMovementCreateProductLotId';
import type { StockMovementCreateDateof } from './stockMovementCreateDateof';
import type { StockMovementCreateQuantity } from './stockMovementCreateQuantity';
import type { StockMovementCreateComment } from './stockMovementCreateComment';

export interface StockMovementCreate {
  area_id: string;
  product_id: string;
  product_lot_id?: StockMovementCreateProductLotId;
  direction: string;
  operation: string;
  dateof: StockMovementCreateDateof;
  quantity?: StockMovementCreateQuantity;
  comment?: StockMovementCreateComment;
  created_by: string;
  initiated_by: string;
  operation_id: string;
}
