/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementReadDateof } from './stockMovementReadDateof';
import type { StockMovementReadQuantity } from './stockMovementReadQuantity';
import type { StockMovementReadComment } from './stockMovementReadComment';

export interface StockMovementRead {
  area_id: number;
  product_id: number;
  direction: string;
  operation: string;
  dateof: StockMovementReadDateof;
  quantity?: StockMovementReadQuantity;
  comment?: StockMovementReadComment;
  id: number;
  dateOf: Date;
}
