/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */

export interface Token {
  access_token: string;
  token_type?: string;
  expires_at: string;
}
