/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateMeName } from './userUpdateMeName';
import type { UserUpdateMeLastName } from './userUpdateMeLastName';
import type { UserUpdateMeEmail } from './userUpdateMeEmail';

export interface UserUpdateMe {
  name?: UserUpdateMeName;
  last_name?: UserUpdateMeLastName;
  email?: UserUpdateMeEmail;
}
