/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateName } from './userUpdateName';
import type { UserUpdateLastName } from './userUpdateLastName';
import type { UserUpdateEmail } from './userUpdateEmail';
import type { UserUpdatePassword } from './userUpdatePassword';
import type { UserUpdateIsPasswordReinitialized } from './userUpdateIsPasswordReinitialized';
import type { UserUpdateIsActive } from './userUpdateIsActive';
import type { UserUpdateIsSuperuser } from './userUpdateIsSuperuser';
import type { UserUpdateIsOwner } from './userUpdateIsOwner';
import type { UserUpdatePhone } from './userUpdatePhone';
import type { UserUpdateOwnedAres } from './userUpdateOwnedAres';
import type { UserUpdateRoles } from './userUpdateRoles';

export interface UserUpdate {
  name: UserUpdateName;
  last_name?: UserUpdateLastName;
  email: UserUpdateEmail;
  password: UserUpdatePassword;
  is_password_reinitialized: UserUpdateIsPasswordReinitialized;
  is_active: UserUpdateIsActive;
  is_superuser: UserUpdateIsSuperuser;
  is_owner: UserUpdateIsOwner;
  phone: UserUpdatePhone;
  owned_ares: UserUpdateOwnedAres;
  roles: UserUpdateRoles;
}
