/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */

export type UsersOwnersListSortBy = typeof UsersOwnersListSortBy[keyof typeof UsersOwnersListSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersOwnersListSortBy = {
  id: 'id',
  last_name: 'last_name',
  created_at: 'created_at',
} as const;
