/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { AreaRead } from './areaRead';

export type UserReadOwnedAreas = AreaRead[] | null;
