/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UserAuthName } from './userAuthName';
import type { UserAuthPhone } from './userAuthPhone';
import type { UserAuthCreatedAt } from './userAuthCreatedAt';
import type { RoleRead } from './roleRead';

export interface UserAuth {
  email: string;
  is_active: boolean;
  is_superuser: boolean;
  is_owner: boolean;
  name?: UserAuthName;
  last_name: string;
  phone: UserAuthPhone;
  created_at?: UserAuthCreatedAt;
  id: string;
  roles: RoleRead[];
}
