/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */

export type UsersOwnersListOrder = typeof UsersOwnersListOrder[keyof typeof UsersOwnersListOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersOwnersListOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
