/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { RoleRead } from './roleRead';

export type UserUpdateRoles = RoleRead[] | null;
