/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateName } from './userCreateName';
import type { UserCreatePhone } from './userCreatePhone';
import type { UserCreateCreatedAt } from './userCreateCreatedAt';
import type { UserCreateEmployeeId } from './userCreateEmployeeId';

export interface UserCreate {
  email: string;
  is_active: boolean;
  is_superuser: boolean;
  is_owner: boolean;
  name?: UserCreateName;
  last_name: string;
  phone: UserCreatePhone;
  created_at?: UserCreateCreatedAt;
  password: string;
  employee_id?: UserCreateEmployeeId;
}
