/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadName } from './userReadName';
import type { UserReadPhone } from './userReadPhone';
import type { UserReadCreatedAt } from './userReadCreatedAt';
import type { UserReadOwnedAreas } from './userReadOwnedAreas';
import type { UserReadEmployee } from './userReadEmployee';
import type { RoleRead } from './roleRead';

export interface UserRead {
  email: string;
  is_active: boolean;
  is_superuser: boolean;
  is_owner: boolean;
  name?: UserReadName;
  last_name: string;
  phone: UserReadPhone;
  created_at?: UserReadCreatedAt;
  id: number;
  is_password_reinitialized: boolean;
  owned_areas?: UserReadOwnedAreas;
  employee: UserReadEmployee;
  roles: RoleRead[];
}
