/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UserRegisterFullName } from './userRegisterFullName';

export interface UserRegister {
  email: string;
  password: string;
  full_name?: UserRegisterFullName;
}
