/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UsersOwnersListSortBy } from './usersOwnersListSortBy';
import type { UsersOwnersListOrder } from './usersOwnersListOrder';

export type UsersOwnersListParams = {
sort_by?: UsersOwnersListSortBy;
order?: UsersOwnersListOrder;
skip?: number;
limit?: number;
};
