/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import type { UserPublicName } from './userPublicName';
import type { UserPublicPhone } from './userPublicPhone';
import type { UserPublicCreatedAt } from './userPublicCreatedAt';

export interface UserPublic {
  email: string;
  is_active: boolean;
  is_superuser: boolean;
  is_owner: boolean;
  name?: UserPublicName;
  last_name: string;
  phone: UserPublicPhone;
  created_at?: UserPublicCreatedAt;
  id: number;
}
