/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';



/**
 * OAuth2 compatible token login, get an access token for future requests
 * @summary Login
 */
export const authLoginResponseTokenTypeDefault = "bearer";

export const authLoginResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().default(authLoginResponseTokenTypeDefault),
  "expires_at": zod.string()
})

