/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Create
 */
export const categoriesCreateBody = zod.object({
  "cat_name": zod.string(),
  "area_id": zod.number()
})

export const categoriesCreateResponse = zod.object({
  "cat_name": zod.string(),
  "area_id": zod.number(),
  "id": zod.number()
})

/**
 * @summary Read
 */
export const categoriesReadParams = zod.object({
  "category_id": zod.number()
})

export const categoriesReadResponse = zod.object({
  "cat_name": zod.string(),
  "area_id": zod.number(),
  "id": zod.number()
})

/**
 * @summary Update
 */
export const categoriesUpdateParams = zod.object({
  "category_id": zod.number()
})

export const categoriesUpdateBody = zod.object({
  "area_id": zod.union([zod.number(),zod.null()]),
  "cat_name": zod.union([zod.string(),zod.null()])
})

export const categoriesUpdateResponse = zod.object({
  "cat_name": zod.string(),
  "area_id": zod.number(),
  "id": zod.number()
})

/**
 * @summary Delete
 */
export const categoriesDeleteParams = zod.object({
  "category_id": zod.number()
})

export const categoriesDeleteQueryParams = zod.object({
  "area_id": zod.number()
})

/**
 * @summary Fetch All
 */
export const categoriesFetchAllParams = zod.object({
  "area_id": zod.number()
})

export const categoriesFetchAllQuerySkipDefault = 0;export const categoriesFetchAllQueryLimitDefault = 10;

export const categoriesFetchAllQueryParams = zod.object({
  "skip": zod.number().optional(),
  "limit": zod.number().default(categoriesFetchAllQueryLimitDefault)
})

export const categoriesFetchAllResponseItem = zod.object({
  "cat_name": zod.string(),
  "area_id": zod.number(),
  "id": zod.number()
})
export const categoriesFetchAllResponse = zod.array(categoriesFetchAllResponseItem)

