/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Read
 */
export const employeeReadParams = zod.object({
  "area_id": zod.uuid(),
  "employee_id": zod.uuid()
})

export const employeeReadResponse = zod.object({
  "first_name": zod.string(),
  "last_name": zod.union([zod.string(),zod.null()]),
  "phone": zod.string(),
  "adress": zod.string(),
  "id": zod.uuid(),
  "area_id": zod.uuid(),
  "user_id": zod.union([zod.uuid(),zod.null()])
})

/**
 * @summary Update
 */
export const employeeUpdateParams = zod.object({
  "area_id": zod.uuid(),
  "employee_id": zod.uuid()
})

export const employeeUpdateBody = zod.object({
  "first_name": zod.union([zod.string(),zod.null()]).optional(),
  "last_name": zod.union([zod.string(),zod.null()]).optional(),
  "phone": zod.union([zod.string(),zod.null()]).optional(),
  "adress": zod.union([zod.string(),zod.null()]).optional()
})

export const employeeUpdateResponse = zod.object({
  "first_name": zod.string(),
  "last_name": zod.union([zod.string(),zod.null()]),
  "phone": zod.string(),
  "adress": zod.string(),
  "id": zod.uuid(),
  "area_id": zod.uuid(),
  "user_id": zod.union([zod.uuid(),zod.null()])
})

/**
 * @summary Delete
 */
export const employeeDeleteParams = zod.object({
  "area_id": zod.uuid(),
  "employee_id": zod.uuid()
})

export const employeeDeleteResponse = zod.object({
  "message": zod.string()
})

/**
 * @summary Create
 */
export const employeeCreateParams = zod.object({
  "area_id": zod.uuid()
})

export const employeeCreateBody = zod.object({
  "first_name": zod.string(),
  "last_name": zod.union([zod.string(),zod.null()]),
  "phone": zod.string(),
  "adress": zod.string(),
  "area_id": zod.uuid()
})

