/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Create
 */
export const movementCreateBody = zod.object({
  "area_id": zod.number(),
  "product_id": zod.number(),
  "direction": zod.string(),
  "operation": zod.string(),
  "dateof": zod.union([zod.iso.datetime({}),zod.null()]),
  "quantity": zod.union([zod.number(),zod.null()]).optional(),
  "comment": zod.union([zod.string(),zod.null()]).optional(),
  "created_by": zod.number(),
  "initiated_by": zod.number(),
  "operation_id": zod.number()
})

/**
 * @summary Read
 */
export const movementReadParams = zod.object({
  "movement_id": zod.number()
})

export const movementReadResponse = zod.object({
  "area_id": zod.number(),
  "product_id": zod.number(),
  "direction": zod.string(),
  "operation": zod.string(),
  "dateof": zod.union([zod.iso.datetime({}),zod.null()]),
  "quantity": zod.union([zod.number(),zod.null()]).optional(),
  "comment": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.number(),
  "dateOf": zod.iso.datetime({})
})

/**
 * @summary Cancel
 */
export const movementCancelParams = zod.object({
  "movement_id": zod.number()
})

/**
 * @summary Product Track
 */
export const movementProductTrackParams = zod.object({
  "product_id": zod.number()
})

export const movementProductTrackQuerySkipDefault = 0;export const movementProductTrackQueryLimitDefault = 10;

export const movementProductTrackQueryParams = zod.object({
  "area_id": zod.number(),
  "date_begin": zod.iso.datetime({}),
  "date_end": zod.iso.datetime({}),
  "skip": zod.number().optional(),
  "limit": zod.number().default(movementProductTrackQueryLimitDefault)
})

export const movementProductTrackResponseItem = zod.object({
  "area_id": zod.number(),
  "product_id": zod.number(),
  "direction": zod.string(),
  "operation": zod.string(),
  "dateof": zod.union([zod.iso.datetime({}),zod.null()]),
  "quantity": zod.union([zod.number(),zod.null()]).optional(),
  "comment": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.number(),
  "dateOf": zod.iso.datetime({})
})
export const movementProductTrackResponse = zod.array(movementProductTrackResponseItem)

