/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Create User
 */
export const privateCreateUserBodyIsVerifiedDefault = false;

export const privateCreateUserBody = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "full_name": zod.string(),
  "is_verified": zod.boolean().optional()
})

export const privateCreateUserResponse = zod.object({
  "email": zod.email(),
  "is_active": zod.boolean(),
  "is_superuser": zod.boolean(),
  "is_owner": zod.boolean(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "last_name": zod.string(),
  "phone": zod.union([zod.string(),zod.null()]),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "id": zod.number()
})

