/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Tantana - Boutik
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Create
 */
export const zoneCreateBody = zod.object({
  "name": zod.string(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "owner_id": zod.union([zod.number(),zod.null()]).optional()
})

/**
 * @summary Read
 */
export const zoneReadParams = zod.object({
  "area_id": zod.number()
})

export const zoneReadResponse = zod.object({
  "name": zod.string(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "owner_id": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number()
})

/**
 * @summary Delete
 */
export const zoneDeleteParams = zod.object({
  "area_id": zod.number()
})

export const zoneDeleteResponse = zod.object({
  "message": zod.string()
})

/**
 * @summary Update
 */
export const zoneUpdateParams = zod.object({
  "area_id": zod.number()
})

export const zoneUpdateResponse = zod.object({
  "data": zod.array(zod.object({
  "email": zod.email(),
  "is_active": zod.boolean(),
  "is_superuser": zod.boolean(),
  "is_owner": zod.boolean(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "last_name": zod.string(),
  "phone": zod.union([zod.string(),zod.null()]),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "id": zod.number()
})),
  "count": zod.number()
})

/**
 * @summary List All
 */
export const zoneListAllResponseItem = zod.object({
  "name": zod.string(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "owner_id": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.number()
})
export const zoneListAllResponse = zod.array(zoneListAllResponseItem)

