#Dockerfile (frontend/DockerFile)
FROM node:24.3.0-alpine as build

WORKDIR /app

COPY package*.json ./
COPY package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
